language: node_js
node_js: '0.10'
script:
  - grunt travis:$TEST
before_install:
  - npm install -g grunt-cli
before_script:
  - grunt lodash
env:
  global:
    - SAUCE_USERNAME=quill
    - SAUCE_ACCESS_KEY=adc0c0cf-221b-46f1-81b9-a4429b722c2e
  matrix:
    - TEST=unit-mac-chrome
addons:
  sauce_connect: true
