language: node_js
node_js: '6'
script:
  - npm run build
  - travis_retry npm run travis
sudo: false
cache:
  directories:
    - node_modules
addons:
  sauce_connect:
    username: "quill"
  jwt:
    secure: "dMtG5IegpgaLnmxvWEnQdfD9GsJSSgYxuHe7yKXuFjLt5MbkDRtxssMXxfLGihisIeCExAzi5wmTKIcQ9sy+HtmE1jJ5s+vGvtNL3NKS2yPZNq+aiXpjlxW5stXQQuFSREi1dfC9oe0InuPkgW3BTs+kV/iLS8ih1+FyegKPwX4="
env:
  matrix:
    - BROWSER=mac-chrome-latest
