name: Unit Tests
on:
  workflow_call:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - run: npm ci
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 1
      - run: npm run test:fuzz
