name: Generate Changelog

on:
  release:
    types: [published]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - run: npm ci
      - run: node ./scripts/changelog.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
