name: Pull Requests

on:
  pull_request:
    branches: [develop]

jobs:
  unit:
    uses: ./.github/workflows/_unit.yml
  fuzz:
    uses: ./.github/workflows/_fuzz.yml
  e2e:
    uses: ./.github/workflows/_e2e.yml
